spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogsys?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/**/*.xml